import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Topbar from "@/components/Topbar/Topbar";
import Sidebar from "@/components/Sidebar/Sidebar";
import globals from "./globals.module.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
  currentPath
}: Readonly<{
	children: React.ReactNode;
  currentPath: string
}>) {

	return (
		<html lang="pt-br">
			<body className={inter.className}>
				<Topbar />
				<Sidebar currentPath={currentPath} />
				{children}
			</body>
		</html>
	);
}
